#
#  Settings for using a mySQL database
###
MySQL:
  Enabled: false
  Username: UserName
  Password: UserPassword
  Database-Name: DataBaseName
  Server:
    SSL: false
    Port: 3306
    Address: localhost

#
# Settings for mcMMO compatibility
#
# Enabled: (true/false) Is the support enabled?
# Tokens-To-Levels: (any whole number) How many mcMMO levels are allowed per token?
###
mcMMO:
  Enabled: false
  Tokens-To-Levels: 1

#
#  Settings for Factions compatibility
#
#  Enabled: (true/false) Is the support enabled?
#  Tokens-To-Power: (any number) How much faction power is 1 token worth?
#
###
Factions:
  Enabled: false
  Tokens-To-Power: 2

#
# Settings for Vault Economy compatibility
#
# Enabled: (true/false) Is support enabled?
# Buy-Tokens: (true/false) Can users buy tokens with in-game currency?
#  Price: (any number) How much is it to purchase one token?
# Sell-Tokens: (true/false) Can users sell tokens for in-game currency?
#  Price: (any number) How much is it for a user to sell one token?
#
###
VaultEco:
  Enabled: false
  Buy-Tokens: false
  Buy-Price: 1500
  Sell-Tokens: true
  Sell-Price: 1000